### ISSUE TITLE
Get a switch to https://gitlab.gnome.org/thiblahute/matrix-dl to select the output format

### ISSUE THREAD

**Issue by thiblahute** [shawntabrizi/matrix-dl-csv#1]
I was wondering if you shouldn't make a MR against my repo with a swicth instead of having another project?

**Comment by shawntabrizi** [comment]
@thiblahute sure, happy to contribute upstream if you would accept that.

**Comment by shawntabrizi** [comment]
https://gitlab.gnome.org/thiblahute/matrix-dl/-/merge_requests/5
